---
- name: Mount rw
  shell: /opt/bin/mount-rw -n
  ignore_errors: yes
- name: Install package monit
  apt: name=monit state=latest update_cache=yes
- file: path=/etc/init.d/monit state=absent
- name: install systemd service
  copy: src=monit.service dest=/lib/systemd/system/monit.service owner=root group=root mode=0755
- name: install rc script
  copy: src=monitrc dest=/etc/monit/monitrc owner=root group=root mode=0600
- name: install cron script
  copy: src=monit.cron dest=/etc/cron.daily/monit owner=root group=root mode=0755
#- name: Remove logrotate config
#  file: path=/etc/logrotate.d/monit state=absent
#- copy: src=conf.d/system.conf dest=/etc/monit/conf.d/system.conf owner=root group=root mode=0644
- file: path=/etc/monit/conf.d/system.conf state=absent
#- name: Configure host system monitoring
#  lineinfile: dest=/etc/monit/conf.d/system.conf regexp='^check system' line='check system {{ansible_fqdn}}'
- copy: src=conf.d/ntp.conf dest=/etc/monit/conf.d/ntp.conf owner=root group=root mode=0644
- copy: src=conf.d/sshd.conf dest=/etc/monit/conf.d/sshd.conf owner=root group=root mode=0644
- systemd: name=monit enabled=yes
- name: Mount ro
  shell: /opt/bin/mount-ro
  ignore_errors: yes
- name: restart monit
  systemd: state=restarted daemon_reload=yes name=monit



