---
- name: include_vars
  include_vars: mailserver.yml
- stat:
    path: /etc/monit/conf.d
  register: st
- fail:
    msg: "Please install monit first"
  when: st.stat.isdir is not defined or st.stat.isdir == False

- name: Mount rw
  ignore_errors: yes
  shell: /opt/bin/mount-rw -n
# Cleanup old postfix install
#- name: remove postfix
#  apt: name=postfix state=absent purge=yes
#  ignore_errors: yes
- name: Stop postfix
  systemd: state=stopped name=postfix
  ignore_errors: yes
- name: remove nullmailer
  apt: name=nullmailer state=absent purge=yes
  ignore_errors: yes
- name: Remove /var/mail
  shell: rm -rf /var/mail && rm -rf /var/mail.dist && rm -rf /var/spool/mail
  ignore_errors: yes
- name: Remove /var/spool/postfix
  shell: rm -rf /var/spool/postfix && rm -rf /var/spool/postfix.dist
  ignore_errors: yes
- name: Remove /var/lib/postfix
  shell: rm -rf /var/lib/postfix && rm -rf /var/lib/postfix.dist
  ignore_errors: yes
- name: Remove /tmp/postfix
  shell: rm -rf /tmp/postfix
  ignore_errors: yes

- name: Install postfix
  shell: DEBIAN_FRONTEND=noninteractive apt-get -y install --reinstall postfix
  ignore_errors: yes
- name: Install mailutils.
  apt: "name={{ item }} state=installed update_cache=yes"
  with_items:
    - mailutils
- name: Setup mailname
  shell: /bin/hostname > /etc/mailname
- name: stop postfix
  systemd: state=stopped name=postfix
# Setup main.cf
- template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
# Setup canonical
- template:
    src: canonical.j2
    dest: /etc/postfix/canonical
    owner: root
    group: root
    mode: 0644
- name: postmap canonical
  shell: postmap /etc/postfix/canonical
# Setup aliases
- template: 
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
- name: newaliases
  shell: newaliases
# smtp_auth
- template:
    src: smtp_auth.j2
    dest: /etc/postfix/smtp_auth
    owner: root
    group: root
    mode: 0644
- name: postmap smtp_auth
  shell: postmap /etc/postfix/smtp_auth
# init script
- name: Install initscript
  copy: src=postfix.initd dest=/etc/init.d/postfix owner=root group=root mode=0755
# Move lots of state/config to tmp
- name: /tmp/postfix
  shell: if [ ! -d /tmp/postfix ]; then mkdir -p /tmp/postfix; fi
- name: /var/spool/postfix.dist
  shell: if [ ! -d /var/spool/postfix.dist ]; then mv /var/spool/postfix /var/spool/postfix.dist; fi
- name: /tmp/postfix/spool
  shell: cp -a /var/spool/postfix.dist /tmp/postfix/spool && ln -s /tmp/postfix/spool /var/spool/postfix
- name: /var/lib/postfix.dist
  shell: if [ ! -d /var/lib/postfix.dist ]; then mv /var/lib/postfix /var/lib/postfix.dist && rm -rf /var/lib/postfix.dist/*; fi
- name: /tmp/postfix/lib
  shell: cp -a /var/lib/postfix.dist /tmp/postfix/lib && ln -s /tmp/postfix/lib /var/lib/postfix
# Finally restart services
- name: Restart postfix
  systemd: state=restarted name=postfix daemon_reload=yes enabled=yes
- name: Add monit config
  copy: src=postfix.monit dest=/etc/monit/conf.d/postfix.conf owner=root group=root mode=0644
- name: Restart monit
  systemd: state=restarted name=monit
- name: Send test email
  shell: mail -s "test from {{ ansible_fqdn }}" root < /etc/motd
- name: Mount ro
  ignore_errors: yes
  shell: /opt/bin/mount-ro

