---
# Configures and updates apt (pi)
- name: Mount rw
  ignore_errors: yes
  shell: /opt/bin/mount-rw -n
- name: Disable ssh root login with password
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin without-password'
- name: Disable ssh login with password
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line='PasswordAuthentication no'
- name: Restart ssh server
  systemd: state=restarted daemon_reload=yes name=ssh enabled=yes
- name: Install apt sources.list
  copy: src=~/dev/embedded_debian/fs/etc/apt/sources.list.pi dest=/etc/apt/sources.list owner=root group=root mode=0644
- name: Install aptitude.
  apt: "name={{ item }} state=installed update_cache=yes"
  with_items:
    - aptitude
    - rpi-update
- name: apt-get upgrade
  apt: update_cache=no upgrade=full
- name: rpi-update
  shell: /usr/bin/rpi-update
- name: Mount ro (You need to check /boot/config.txt and then reboot)
  ignore_errors: yes
  shell: /opt/bin/mount-ro
