# Setup ssh server
---
- name: Disable ssh root login with password
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin without-password'
- name: Disable ssh login with password
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line='PasswordAuthentication no'
- name: Restart ssh server
  systemd: state=restarted daemon_reload=yes name=ssh enabled=yes
