---
- name: Download bcm2835 library.
  get_url:
    url: "http://www.airspayce.com/mikem/bcm2835/bcm2835-1.50.tar.gz"
    dest: "{{ ansible_user_dir }}/bcm2835-1.50.tar.gz"
- name: Expand bcm2835 archive.
  unarchive:
    src: "{{ ansible_user_dir }}/bcm2835-1.50.tar.gz"
    dest: "{{ ansible_user_dir }}"
    creates: "{{ ansible_user_dir }}/bcm2835-1.50/README"
    remote_src: yes
- name: Build and install bcm2835 lib
  shell: cd {{ ansible_user_dir }}/bcm2835-1.50 && ./configure && make && make check && make install 
- npm: name=node-dht-sensor path=/usr/lib/node_modules/node-red/node_modules
- npm: name=node-red-contrib-dht-sensor path=/usr/lib/node_modules/node-red/node_modules

