---
# This does servers_virtual setup @ https://wiki.mjwconsult.co.uk/doku.php?id=systems:servers_virtual:20150506
- hosts: debian_servers
  remote_user: root
  tasks:
  - name: Disable ssh root login with password
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' line='PermitRootLogin without-password'
  - name: Disable ssh login with password
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication' line='PasswordAuthentication no'
  - name: Restart ssh server
    systemd: state=restarted daemon_reload=yes name=ssh enabled=yes
  - name: Install apt sources.list
    copy: src=~/dev/embedded_debian/fs/etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  - name: apt-get upgrade
    apt: update_cache=yes upgrade=full
  - name: Install standard packages.
    apt: "name={{ item }} state=installed"
    with_items:
      - vim
      - acpi
      - acpi-support-base
  - shell: /bin/rm -f /etc/acpi/event/powerbtn

/etc/bash.bashrc:
# enable bash completion in interactive shells
#if ! shopt -oq posix; then
#  if [ -f /usr/share/bash-completion/bash_completion ]; then
#    . /usr/share/bash-completion/bash_completion
#  elif [ -f /etc/bash_completion ]; then
#    . /etc/bash_completion
#  fi
#fi

/etc/vim/vimrc:
syntax on
set background=dark

