# TODO:
# This needs to detect that we are running new nodered and not re-do an apt/update
---
- hosts: embedded
  remote_user: root
  tasks:
  - name: Mount rw
    shell: /opt/bin/mount-rw -n
#  - name: Install package nodered
#    apt: name=nodered state=latest update_cache=no
#  - systemd: name=nodered enabled=yes
  - name: Ensure build dependencies are installed.
    apt: "name={{ item }} state=installed"
    with_items:
      - build-essential
      - gcc
      - make
      - npm
#  - name: Update nodejs and nodered
#    shell: yes | update-nodejs-and-nodered
  - name: Download nodered.service file.
      copy: src=~/dev/embedded_debian/apps/nodered/nodered.service dest=/lib/systemd/system/nodered.service owner=root group=root mode=0755
  - name: Download node-red-start.
    get_url:
      url: "https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-start"
      dest: "/usr/bin/node-red-start"
      mode: 0755
  - name: Download node-red-stop.
    get_url:
      url: "https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/node-red-stop"
      dest: "/usr/bin/node-red-stop"
      mode: 0755
  - name: Download bcm2835 library.
    get_url:
      url: "http://www.airspayce.com/mikem/bcm2835/bcm2835-1.50.tar.gz"
      dest: "{{ ansible_user_dir }}/bcm2835-1.50.tar.gz"
  - name: Expand bcm2835 archive.
    unarchive:
      src: "{{ ansible_user_dir }}/bcm2835-1.50.tar.gz"
      dest: "{{ ansible_user_dir }}"
      creates: "{{ ansible_user_dir }}/bcm2835-1.50/README"
      remote_src: yes
#  - name: Build and install bcm2835 lib
#    shell: cd {{ ansible_user_dir }}/bcm2835-1.50 && ./configure && make && make check && make install 
#  - npm: name=node-dht-sensor path=/usr/lib/node_modules/node-red/node_modules
#  - npm: name=node-red-contrib-dht-sensor path=/usr/lib/node_modules/node-red/node_modules
#  - npm: name=node-red-node-emoncms path=/usr/lib/node_modules/node-red/node_modules
#  - npm: name=node-red-contrib-collector path=/usr/lib/node_modules/node-red/node_modules
    notify:
    - restart nodered
  - name: Add monit config
    copy: src=~/dev/embedded_debian/apps/nodered/nodered.monit dest=/etc/monit/conf.d/nodered.conf owner=root group=root mode=0644
    notify:
    - reload monit
  - name: Mount ro
    shell: /opt/bin/mount-ro

  handlers:
    - name: restart nodered
      systemd: state=restarted daemon_reload=yes name=nodered
    - name: reload monit
      shell: /usr/bin/monit reload


